// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFBgdA2IL1-_1KVsNVxvt3LsjuuIrO-P4',
    appId: '1:196433340076:web:dbed3a3c3ac3733417e109',
    messagingSenderId: '196433340076',
    projectId: 'carlog-nutzu',
    authDomain: 'carlog-nutzu.firebaseapp.com',
    storageBucket: 'carlog-nutzu.firebasestorage.app',
    measurementId: 'G-FSQJWX953C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA320Jffo0Uc3sNz2dygx1_guLSsJW_0JA',
    appId: '1:196433340076:android:11b71d3fa7a0d02717e109',
    messagingSenderId: '196433340076',
    projectId: 'carlog-nutzu',
    storageBucket: 'carlog-nutzu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh6CTL2IKYxrWxZLTx8vk_kL_TeemD2-M',
    appId: '1:196433340076:ios:e665138be276609817e109',
    messagingSenderId: '196433340076',
    projectId: 'carlog-nutzu',
    storageBucket: 'carlog-nutzu.firebasestorage.app',
    iosBundleId: 'com.example.carlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh6CTL2IKYxrWxZLTx8vk_kL_TeemD2-M',
    appId: '1:196433340076:ios:e665138be276609817e109',
    messagingSenderId: '196433340076',
    projectId: 'carlog-nutzu',
    storageBucket: 'carlog-nutzu.firebasestorage.app',
    iosBundleId: 'com.example.carlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFBgdA2IL1-_1KVsNVxvt3LsjuuIrO-P4',
    appId: '1:196433340076:web:93bcf74dacf3859417e109',
    messagingSenderId: '196433340076',
    projectId: 'carlog-nutzu',
    authDomain: 'carlog-nutzu.firebaseapp.com',
    storageBucket: 'carlog-nutzu.firebasestorage.app',
    measurementId: 'G-4S99ZHWCEK',
  );
}
