import 'models.dart';

final List<Vehicle> mockVehicles = [
  const Vehicle(
    id: 'v1',
    brand: 'Volkswagen',
    model: 'Passat',
    year: 2018,
    engine: '2.0 TDI',
    vin: 'WVWZZZ3CZJE000001',
    mileage: 168000,
  ),
  const Vehicle(
    id: 'v2',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2022,
    engine: 'Long Range',
    vin: '5YJ3E1EA7KF000003',
    mileage: 24000,
  ),
  const Vehicle(
    id: 'v3',
    brand: 'Porsche',
    model: 'Cayenne',
    year: 2023,
    engine: '3.0 Hybrid',
    vin: 'WP1ZZZ9YZPA000004',
    mileage: 22000,
  ),
];

final List<CarExpense> mockExpenses = [
  // Last 6 months - Volkswagen Passat (v1)
  CarExpense(
    id: 'e1',
    amount: 305,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 4)),
    description: 'Diesel - full tank (OMV)',
    mileage: 167920,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e2',
    amount: 320,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 16)),
    description: 'Diesel - city + highway mix',
    mileage: 167480,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e3',
    amount: 180,
    category: ExpenseCategory.parts,
    date: DateTime.now().subtract(const Duration(days: 28)),
    description: 'Windshield wipers + cabin filter',
    mileage: 167050,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e4',
    amount: 310,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 42)),
    description: 'Diesel - full tank (Lukoil)',
    mileage: 166620,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e5',
    amount: 1450,
    category: ExpenseCategory.service,
    date: DateTime.now().subtract(const Duration(days: 58)),
    description: 'Major service + timing belt kit',
    mileage: 166100,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e6',
    amount: 295,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 73)),
    description: 'Diesel - business trip refill',
    mileage: 165520,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e7',
    amount: 315,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 90)),
    description: 'Diesel - full tank (Rompetrol)',
    mileage: 164980,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e8',
    amount: 120,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 108)),
    description: 'Car wash package + interior cleaning',
    mileage: 164300,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e9',
    amount: 780,
    category: ExpenseCategory.insurance,
    date: DateTime.now().subtract(const Duration(days: 126)),
    description: 'RCA renewal + roadside assistance',
    mileage: 163650,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e10',
    amount: 300,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 144)),
    description: 'Diesel - monthly refill',
    mileage: 162980,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e11',
    amount: 260,
    category: ExpenseCategory.parts,
    date: DateTime.now().subtract(const Duration(days: 165)),
    description: 'Front brake pads replacement',
    mileage: 162120,
    vehicleId: 'v1',
  ),

  // Last 6 months - Tesla Model 3 (v2)
  CarExpense(
    id: 'e12',
    amount: 115,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 2)),
    description: 'Supercharger session (highway)',
    mileage: 23980,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e13',
    amount: 95,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 14)),
    description: 'Charging at DC station (city)',
    mileage: 23690,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e14',
    amount: 70,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 24)),
    description: 'Touchless wash + vacuum',
    mileage: 23490,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e15',
    amount: 118,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 37)),
    description: 'Supercharger - weekend trip',
    mileage: 23220,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e16',
    amount: 420,
    category: ExpenseCategory.service,
    date: DateTime.now().subtract(const Duration(days: 53)),
    description: 'Tire rotation + wheel balancing',
    mileage: 22840,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e17',
    amount: 102,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 67)),
    description: 'Fast charging - mixed route',
    mileage: 22590,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e18',
    amount: 112,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 82)),
    description: 'Supercharger session',
    mileage: 22270,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e19',
    amount: 89,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 101)),
    description: 'Public charging (AC + DC mix)',
    mileage: 21820,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e20',
    amount: 1600,
    category: ExpenseCategory.insurance,
    date: DateTime.now().subtract(const Duration(days: 121)),
    description: 'CASCO annual policy',
    mileage: 21380,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e21',
    amount: 105,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 143)),
    description: 'Supercharger - monthly travel',
    mileage: 20740,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e22',
    amount: 96,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 170)),
    description: 'Charging before long trip',
    mileage: 19950,
    vehicleId: 'v2',
  ),

  // Last 6 months - Porsche Cayenne (v3)
  CarExpense(
    id: 'e23',
    amount: 450,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 3)),
    description: 'Petrol + charge top-up (hybrid)',
    mileage: 21960,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e24',
    amount: 470,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 18)),
    description: 'Premium petrol refill (highway trip)',
    mileage: 21680,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e25',
    amount: 260,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 31)),
    description: 'Premium wash & detailing',
    mileage: 21490,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e26',
    amount: 2250,
    category: ExpenseCategory.service,
    date: DateTime.now().subtract(const Duration(days: 49)),
    description: 'Scheduled inspection at Porsche Center',
    mileage: 21210,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e27',
    amount: 440,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 66)),
    description: 'Petrol refill + parking fees',
    mileage: 20880,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e28',
    amount: 1820,
    category: ExpenseCategory.parts,
    date: DateTime.now().subtract(const Duration(days: 85)),
    description: 'Front tires replacement',
    mileage: 20450,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e29',
    amount: 455,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 103)),
    description: 'Premium petrol - city + highway',
    mileage: 20120,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e30',
    amount: 1850,
    category: ExpenseCategory.insurance,
    date: DateTime.now().subtract(const Duration(days: 124)),
    description: 'CASCO renewal',
    mileage: 19720,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e31',
    amount: 430,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 147)),
    description: 'Premium petrol refill (Mol)',
    mileage: 19260,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e32',
    amount: 380,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 172)),
    description: 'Ceramic maintenance wash package',
    mileage: 18650,
    vehicleId: 'v3',
  ),
];

final List<MaintenanceReminder> mockReminders = [
  MaintenanceReminder(
    id: 'm1',
    title: 'Oil change',
    description: 'Recommended every 15.000 km or 12 months.',
    dueMileage: 180000,
    vehicleId: 'v1',
  ),
  MaintenanceReminder(
    id: 'm2',
    title: 'ITP (Romanian inspection)',
    description: 'Next technical inspection for Passat.',
    dueDate: DateTime.now().add(const Duration(days: 90)),
    vehicleId: 'v1',
  ),
  MaintenanceReminder(
    id: 'm3',
    title: 'Tire rotation',
    description: 'Rotate tires and check alignment.',
    dueMileage: 26000,
    vehicleId: 'v2',
  ),
  MaintenanceReminder(
    id: 'm4',
    title: 'Hybrid system check',
    description: 'Check high-voltage battery and cooling system.',
    dueDate: DateTime.now().add(const Duration(days: 120)),
    vehicleId: 'v3',
  ),
];
