import 'models.dart';

final List<Vehicle> mockVehicles = [
  const Vehicle(
    id: 'v1',
    brand: 'Volkswagen',
    model: 'Passat',
    year: 2018,
    engine: '2.0 TDI',
    fuelType: VehicleFuelType.diesel,
    vin: 'WVWZZZ3CZJE000001',
    mileage: 168000,
  ),
  const Vehicle(
    id: 'v2',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2022,
    engine: 'Long Range',
    fuelType: VehicleFuelType.electric,
    vin: '5YJ3E1EA7KF000003',
    mileage: 24000,
  ),
  const Vehicle(
    id: 'v3',
    brand: 'Porsche',
    model: 'Cayenne',
    year: 2023,
    engine: '3.0 Hybrid',
    fuelType: VehicleFuelType.hybrid,
    vin: 'WP1ZZZ9YZPA000004',
    mileage: 22000,
  ),
];

final List<CarExpense> mockExpenses = [
  // Last 6 months - Volkswagen Passat (v1)
  CarExpense(
    id: 'e1',
    amount: 305,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 4)),
    description: 'Diesel - full tank (OMV)',
    mileage: 167920,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e2',
    amount: 320,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 16)),
    description: 'Diesel - city + highway mix',
    mileage: 167480,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e3',
    amount: 180,
    category: ExpenseCategory.parts,
    date: DateTime.now().subtract(const Duration(days: 28)),
    description: 'Windshield wipers + cabin filter',
    mileage: 167050,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e4',
    amount: 310,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 42)),
    description: 'Diesel - full tank (Lukoil)',
    mileage: 166620,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e5',
    amount: 1450,
    category: ExpenseCategory.service,
    date: DateTime.now().subtract(const Duration(days: 58)),
    description: 'Major service + timing belt kit',
    mileage: 166100,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e6',
    amount: 295,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 73)),
    description: 'Diesel - business trip refill',
    mileage: 165520,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e7',
    amount: 315,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 90)),
    description: 'Diesel - full tank (Rompetrol)',
    mileage: 164980,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e8',
    amount: 120,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 108)),
    description: 'Car wash package + interior cleaning',
    mileage: 164300,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e9',
    amount: 780,
    category: ExpenseCategory.insurance,
    date: DateTime.now().subtract(const Duration(days: 126)),
    description: 'RCA renewal + roadside assistance',
    mileage: 163650,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e10',
    amount: 300,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 144)),
    description: 'Diesel - monthly refill',
    mileage: 162980,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e11',
    amount: 260,
    category: ExpenseCategory.parts,
    date: DateTime.now().subtract(const Duration(days: 165)),
    description: 'Front brake pads replacement',
    mileage: 162120,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e33',
    amount: 285,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 191)),
    description: 'Diesel - intercity refill',
    mileage: 161540,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e34',
    amount: 640,
    category: ExpenseCategory.service,
    date: DateTime.now().subtract(const Duration(days: 214)),
    description: 'Rear shocks and alignment',
    mileage: 160980,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e35',
    amount: 292,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 231)),
    description: 'Diesel - monthly refill',
    mileage: 160420,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e36',
    amount: 95,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 248)),
    description: 'Road vignette and washer fluid',
    mileage: 159980,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e37',
    amount: 280,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 273)),
    description: 'Diesel - commuter refill',
    mileage: 159360,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e38',
    amount: 470,
    category: ExpenseCategory.parts,
    date: DateTime.now().subtract(const Duration(days: 297)),
    description: 'Battery replacement',
    mileage: 158900,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e39',
    amount: 275,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 325)),
    description: 'Diesel - long weekend travel',
    mileage: 158240,
    vehicleId: 'v1',
  ),
  CarExpense(
    id: 'e40',
    amount: 310,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 352)),
    description: 'Diesel - holiday season refill',
    mileage: 157680,
    vehicleId: 'v1',
  ),

  // Last 6 months - Tesla Model 3 (v2)
  CarExpense(
    id: 'e12',
    amount: 115,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 2)),
    description: 'Supercharger session (highway)',
    mileage: 23980,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e13',
    amount: 95,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 14)),
    description: 'Charging at DC station (city)',
    mileage: 23690,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e14',
    amount: 70,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 24)),
    description: 'Touchless wash + vacuum',
    mileage: 23490,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e15',
    amount: 118,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 37)),
    description: 'Supercharger - weekend trip',
    mileage: 23220,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e16',
    amount: 420,
    category: ExpenseCategory.service,
    date: DateTime.now().subtract(const Duration(days: 53)),
    description: 'Tire rotation + wheel balancing',
    mileage: 22840,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e17',
    amount: 102,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 67)),
    description: 'Fast charging - mixed route',
    mileage: 22590,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e18',
    amount: 112,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 82)),
    description: 'Supercharger session',
    mileage: 22270,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e19',
    amount: 89,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 101)),
    description: 'Public charging (AC + DC mix)',
    mileage: 21820,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e20',
    amount: 1600,
    category: ExpenseCategory.insurance,
    date: DateTime.now().subtract(const Duration(days: 121)),
    description: 'CASCO annual policy',
    mileage: 21380,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e21',
    amount: 105,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 143)),
    description: 'Supercharger - monthly travel',
    mileage: 20740,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e22',
    amount: 96,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 170)),
    description: 'Charging before long trip',
    mileage: 19950,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e41',
    amount: 101,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 196)),
    description: 'Supercharger - business trip',
    mileage: 19480,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e42',
    amount: 210,
    category: ExpenseCategory.service,
    date: DateTime.now().subtract(const Duration(days: 219)),
    description: 'Cabin air filter and brake fluid check',
    mileage: 19150,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e43',
    amount: 92,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 236)),
    description: 'Public charging - city usage',
    mileage: 18880,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e44',
    amount: 58,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 255)),
    description: 'Glass treatment and wash',
    mileage: 18620,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e45',
    amount: 108,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 279)),
    description: 'Supercharger - out of town trip',
    mileage: 18270,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e46',
    amount: 390,
    category: ExpenseCategory.parts,
    date: DateTime.now().subtract(const Duration(days: 305)),
    description: 'New set of aero wheel covers',
    mileage: 17890,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e47',
    amount: 98,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 332)),
    description: 'Charging before airport run',
    mileage: 17480,
    vehicleId: 'v2',
  ),
  CarExpense(
    id: 'e48',
    amount: 88,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 358)),
    description: 'Home + public charging top-up',
    mileage: 17120,
    vehicleId: 'v2',
  ),

  // Last 6 months - Porsche Cayenne (v3)
  CarExpense(
    id: 'e23',
    amount: 450,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 3)),
    description: 'Petrol + charge top-up (hybrid)',
    mileage: 21960,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e24',
    amount: 470,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 18)),
    description: 'Premium petrol refill (highway trip)',
    mileage: 21680,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e25',
    amount: 260,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 31)),
    description: 'Premium wash & detailing',
    mileage: 21490,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e26',
    amount: 2250,
    category: ExpenseCategory.service,
    date: DateTime.now().subtract(const Duration(days: 49)),
    description: 'Scheduled inspection at Porsche Center',
    mileage: 21210,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e27',
    amount: 440,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 66)),
    description: 'Petrol refill + parking fees',
    mileage: 20880,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e28',
    amount: 1820,
    category: ExpenseCategory.parts,
    date: DateTime.now().subtract(const Duration(days: 85)),
    description: 'Front tires replacement',
    mileage: 20450,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e29',
    amount: 455,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 103)),
    description: 'Premium petrol - city + highway',
    mileage: 20120,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e30',
    amount: 1850,
    category: ExpenseCategory.insurance,
    date: DateTime.now().subtract(const Duration(days: 124)),
    description: 'CASCO renewal',
    mileage: 19720,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e31',
    amount: 430,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 147)),
    description: 'Premium petrol refill (Mol)',
    mileage: 19260,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e32',
    amount: 380,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 172)),
    description: 'Ceramic maintenance wash package',
    mileage: 18650,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e49',
    amount: 425,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 194)),
    description: 'Premium petrol refill before weekend trip',
    mileage: 18320,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e50',
    amount: 760,
    category: ExpenseCategory.service,
    date: DateTime.now().subtract(const Duration(days: 217)),
    description: 'Brake fluid service and diagnostics',
    mileage: 17980,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e51',
    amount: 410,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 236)),
    description: 'Premium petrol - city driving',
    mileage: 17620,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e52',
    amount: 195,
    category: ExpenseCategory.other,
    date: DateTime.now().subtract(const Duration(days: 258)),
    description: 'Seasonal detailing and leather care',
    mileage: 17280,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e53',
    amount: 438,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 284)),
    description: 'Premium petrol refill (high-speed travel)',
    mileage: 16890,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e54',
    amount: 1480,
    category: ExpenseCategory.parts,
    date: DateTime.now().subtract(const Duration(days: 308)),
    description: 'Rear brake discs and pads',
    mileage: 16540,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e55',
    amount: 402,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 336)),
    description: 'Premium petrol - monthly refill',
    mileage: 16110,
    vehicleId: 'v3',
  ),
  CarExpense(
    id: 'e56',
    amount: 420,
    category: ExpenseCategory.fuel,
    date: DateTime.now().subtract(const Duration(days: 362)),
    description: 'Premium petrol refill before holiday travel',
    mileage: 15760,
    vehicleId: 'v3',
  ),
];

List<MaintenanceReminder> buildMockReminders() {
  final now = DateTime.now();
  final today = DateTime(now.year, now.month, now.day);

  return [
    MaintenanceReminder(
      id: 'm1',
      title: 'Oil change',
      description: 'Recommended every 15.000 km or 12 months.',
      dueMileage: 169200,
      vehicleId: 'v1',
    ),
    MaintenanceReminder(
      id: 'm2',
      title: 'ITP (Romanian inspection)',
      description: 'Next technical inspection for Passat.',
      dueDate: today.add(const Duration(days: 6)),
      vehicleId: 'v1',
    ),
    MaintenanceReminder(
      id: 'm3',
      title: 'Tire rotation',
      description: 'Rotate tires and check alignment.',
      dueMileage: 25500,
      vehicleId: 'v2',
    ),
    MaintenanceReminder(
      id: 'm4',
      title: 'Hybrid system check',
      description: 'Check high-voltage battery and cooling system.',
      dueDate: today.add(const Duration(days: 14)),
      vehicleId: 'v3',
    ),
  ];
}

